import os

from .consts import CACHE_ALGO_XXH64

SECONDS_IN_DAY = 86400
SECONDS_IN_HOUR = 3600
SECONDS_IN_MINUTE = 60

CACHE_DIR_NAME = "__cache__"
CACHE_FILENAME = "cache"
CACHE_DIR = os.path.abspath("./" + CACHE_DIR_NAME)
CACHE_DIR_LEVEL = 2
CACHE_SEGMENT_SIZE = 2
CACHE_FILE_MIN_SIZE = 2 * 1024
CACHE_MAX_AGE = 30 * SECONDS_IN_MINUTE
CACHE_DEFAULT_ALGORITHM = CACHE_ALGO_XXH64
